#!/usr/bin/env bash
# Remove Kube-OVN non-primary CNI artifacts from a physical K3s cluster.
#
# Args:
#   $1: Optional configK3s.yaml path. Defaults to ../configK3s.yaml.
#
# Inputs:
#   configK3s.yaml and the kubeconfig generated by buildK3sCluster.sh.
#
# Side effects:
#   Uninstalls the Kube-OVN Helm release when a live cluster is available and
#   removes Kube-OVN/OVS/OVN runtime files from configured nodes. It does not
#   reboot nodes; users can reboot manually if they need a fully cold network
#   state as recommended by Kube-OVN upstream docs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_PATH="${1:-${SETUP_DIR}/configK3s.yaml}"
HELPER="${SETUP_DIR}/manageK3sConfig.py"

if [ ! -s "${CONFIG_PATH}" ]; then
    echo "Missing config file: ${CONFIG_PATH}" >&2
    exit 1
fi

eval "$(python3 "${HELPER}" --config "${CONFIG_PATH}" shell-vars)"
eval "$(python3 "${HELPER}" --config "${CONFIG_PATH}" ovn-shell-vars)"

if [ "${fabricType}" != "ovn" ] && [ "${fabricType}" != "kube-ovn" ]; then
    echo "No Kube-OVN fabric configured; nothing to clean."
    exit 0
fi

sshOptions() {
    # Args:
    #   $1: SSH private key used for the target node.
    local ssh_key="$1"
    printf '%s\n' \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=ERROR \
        -o ConnectTimeout=10 \
        -i "$ssh_key"
}

runNodeRootScript() {
    # Args:
    #   $1: node name, $2: management IP, $3: connection mode, $4: SSH user,
    #   $5: SSH key, $6: shell script to run as root.
    local name="$1"
    local ip="$2"
    local connection="$3"
    local ssh_user="$4"
    local ssh_key="$5"
    local script="$6"

    echo "[ovn-clean] ${name} (${ip})"
    if [ "${connection}" = "local" ]; then
        sudo -n bash -s <<<"${script}"
        return
    fi

    # shellcheck disable=SC2046
    ssh $(sshOptions "${ssh_key}") "${ssh_user}@${ip}" "sudo -n bash -s" <<<"${script}"
}

ensureHelm() {
    # Print an existing helm binary or the private binary downloaded by
    # installKubeOvnFabric.sh.
    if command -v helm >/dev/null 2>&1; then
        command -v helm
        return
    fi
    local helm_bin="${ovnHelmCacheDir}/bin/helm"
    if [ -x "${helm_bin}" ]; then
        echo "${helm_bin}"
        return
    fi
    echo ""
}

uninstallHelmRelease() {
    # Remove Kubernetes resources while the API server is still available.
    [ -s "${outputKubeconfig}" ] || return 0
    local helm_bin
    helm_bin="$(ensureHelm)"
    if [ -n "${helm_bin}" ]; then
        "${helm_bin}" uninstall "${ovnReleaseName}" -n "${ovnNamespace}" --kubeconfig "${outputKubeconfig}" >/dev/null 2>&1 || true
    else
        kubectl --kubeconfig "${outputKubeconfig}" -n "${ovnNamespace}" delete deploy,ds,sts,svc,cm,sa,role,rolebinding \
            -l app.kubernetes.io/instance="${ovnReleaseName}" --ignore-not-found >/dev/null 2>&1 || true
    fi
}

clean_node_script='
set -euo pipefail
rm -rf /var/run/openvswitch
rm -rf /var/run/ovn
rm -rf /etc/origin/openvswitch
rm -rf /etc/origin/ovn
rm -rf /etc/cni/net.d/00-kube-ovn.conflist
rm -rf /etc/cni/net.d/01-kube-ovn.conflist
rm -rf /var/lib/rancher/k3s/agent/etc/cni/net.d/00-kube-ovn.conflist
rm -rf /var/lib/rancher/k3s/agent/etc/cni/net.d/01-kube-ovn.conflist
rm -rf /var/log/openvswitch
rm -rf /var/log/ovn
rm -rf /var/log/kube-ovn
ip link del ovn0 2>/dev/null || true
'

uninstallHelmRelease
while IFS=$'\t' read -r name role ip mac vcpus memory_mb disk_gb; do
    eval "$(python3 "${HELPER}" --config "${CONFIG_PATH}" node-ssh-vars --name "${name}")"
    runNodeRootScript "${name}" "${ip}" "${nodeConnection}" "${nodeSshUser}" "${nodeSshKey}" "${clean_node_script}"
done < <(python3 "${HELPER}" --config "${CONFIG_PATH}" nodes-tsv)

echo "Kube-OVN fabric cleaned."
