version: "3.4"

services:
  seedemu-legacy:
    build:
      context: ./legacy
      dockerfile: Dockerfile
    image: handsonsecurity/seedemu-ethereum:legacy

  seedemu-pos:
    build:
      context: ./pos
      dockerfile: Dockerfile
    image: handsonsecurity/seedemu-ethereum:pos
    
  seedemu-pos2.0:
    build:
      context: ./pos2.0
      dockerfile: Dockerfile
    image: handsonsecurity/seedemu-ethereum:pos2.0
