#!/usr/bin/env python3
"""Validate native Kubernetes compiler output used by PR checks.

Inputs:
- an output directory generated by mini_internet_k8s.py.

Outputs:
- console diagnostics only.

Side effects:
- none; this script only parses YAML, JSON, and Docker build contexts.

Expected context:
- GitHub-hosted or local developer machine with Python 3.10+ and PyYAML.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import sys
from pathlib import Path
from typing import Any

import yaml


MANIFEST_NAME = "k8s.kube-ovn.yaml"
IMAGES_NAME = "images.yaml"
LEGACY_MANIFEST_NAME = "k8s.yaml"
FORBIDDEN_TEXT = (str(Path("/home") / "lxl") + "/", str(Path("/home") / "lxl"))


def parseArgs() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True, help="Compiler output directory.")
    parser.add_argument("--expected-namespace", required=True, help="Expected Kubernetes namespace name.")
    parser.add_argument(
        "--image-registry-prefix",
        default="seedemu",
        help="Logical image prefix written by NativeKubernetesCompiler.",
    )
    return parser.parse_args()


def fail(message: str) -> None:
    """Exit with a validation failure message.

    Args:
        message: Human-readable validation error.
    """
    raise SystemExit(f"native k8s output validation failed: {message}")


def loadYamlDocuments(path: Path) -> list[dict[str, Any]]:
    """Load a Kubernetes multi-document YAML file.

    Args:
        path: Manifest path.
    """
    docs = [doc for doc in yaml.safe_load_all(path.read_text(encoding="utf-8")) if doc is not None]
    invalid = [doc for doc in docs if not isinstance(doc, dict)]
    if invalid:
        fail(f"{path.name} contains non-mapping YAML documents")
    return docs


def loadImages(path: Path) -> list[dict[str, str]]:
    """Load images.yaml and return image entries.

    Args:
        path: images.yaml path.
    """
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        fail("images.yaml root must be a mapping")
    images = data.get("images")
    if not isinstance(images, list) or not images:
        fail("images.yaml must contain a non-empty images list")
    for item in images:
        if not isinstance(item, dict):
            fail("images.yaml entries must be mappings")
        if not isinstance(item.get("name"), str) or not item["name"].strip():
            fail("images.yaml entry requires non-empty name")
        if not isinstance(item.get("context"), str) or not item["context"].strip():
            fail(f"image {item.get('name')} requires non-empty context")
    return images


def indexKinds(docs: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group Kubernetes documents by kind.

    Args:
        docs: Parsed Kubernetes manifest documents.
    """
    by_kind: dict[str, list[dict[str, Any]]] = {}
    for doc in docs:
        kind = str(doc.get("kind") or "")
        if not kind:
            fail(f"manifest document lacks kind: {doc}")
        by_kind.setdefault(kind, []).append(doc)
    return by_kind


def validateNamespace(by_kind: dict[str, list[dict[str, Any]]], expected_namespace: str) -> None:
    """Validate the compiler-created namespace.

    Args:
        by_kind: Manifest documents grouped by kind.
        expected_namespace: Namespace expected from the example compiler.
    """
    namespaces = by_kind.get("Namespace", [])
    if len(namespaces) != 1:
        fail(f"expected exactly one Namespace, got {len(namespaces)}")
    namespace = str((namespaces[0].get("metadata") or {}).get("name") or "")
    if namespace != expected_namespace:
        fail(f"expected namespace {expected_namespace}, got {namespace}")


def validateRequiredKinds(by_kind: dict[str, list[dict[str, Any]]]) -> None:
    """Validate that Kube-OVN output contains all required resource kinds.

    Args:
        by_kind: Manifest documents grouped by kind.
    """
    required = ("Namespace", "Vpc", "Subnet", "NetworkAttachmentDefinition", "Deployment")
    missing = [kind for kind in required if not by_kind.get(kind)]
    if missing:
        fail(f"manifest missing required kinds: {', '.join(missing)}")


def validateVpcAndSubnets(by_kind: dict[str, list[dict[str, Any]]]) -> None:
    """Validate Kube-OVN Vpc and Subnet resource shape.

    Args:
        by_kind: Manifest documents grouped by kind.
    """
    vpcs = by_kind.get("Vpc", [])
    if len(vpcs) != 1:
        fail(f"expected exactly one Kube-OVN Vpc, got {len(vpcs)}")
    vpc_name = str((vpcs[0].get("metadata") or {}).get("name") or "")
    if not vpc_name:
        fail("Kube-OVN Vpc requires metadata.name")
    for subnet in by_kind.get("Subnet", []):
        spec = subnet.get("spec") or {}
        if spec.get("vpc") != vpc_name:
            fail(f"Subnet {(subnet.get('metadata') or {}).get('name')} does not reference Vpc {vpc_name}")
        provider = str(spec.get("provider") or "")
        if not provider.endswith(".ovn"):
            fail(f"Subnet provider must use Kube-OVN provider suffix: {provider}")
        cidr = str(spec.get("cidrBlock") or "")
        try:
            ipaddress.ip_network(cidr, strict=False)
        except ValueError as exc:
            fail(f"invalid Subnet cidrBlock {cidr}: {exc}")
        if not spec.get("gateway"):
            fail(f"Subnet {(subnet.get('metadata') or {}).get('name')} requires gateway")


def validateNetworkAttachments(by_kind: dict[str, list[dict[str, Any]]]) -> None:
    """Validate that Multus NADs are rendered for Kube-OVN, not macvlan.

    Args:
        by_kind: Manifest documents grouped by kind.
    """
    for nad in by_kind.get("NetworkAttachmentDefinition", []):
        metadata = nad.get("metadata") or {}
        name = str(metadata.get("name") or "")
        spec = nad.get("spec") or {}
        raw_config = spec.get("config")
        if not isinstance(raw_config, str):
            fail(f"NAD {name} requires string spec.config")
        try:
            config = json.loads(raw_config)
        except json.JSONDecodeError as exc:
            fail(f"NAD {name} spec.config is not JSON: {exc}")
        if config.get("type") != "kube-ovn":
            fail(f"NAD {name} must use type kube-ovn, got {config.get('type')}")
        provider = str(config.get("provider") or "")
        if not provider.endswith(".ovn"):
            fail(f"NAD {name} provider must end with .ovn")
        if "master" in config:
            fail(f"NAD {name} still contains macvlan master field")


def podTemplateAnnotations(workload: dict[str, Any]) -> dict[str, Any]:
    """Return workload pod-template annotations.

    Args:
        workload: Deployment-like Kubernetes resource.
    """
    return (
        ((workload.get("spec") or {}).get("template") or {})
        .get("metadata", {})
        .get("annotations", {})
        or {}
    )


def validateDeployments(
    by_kind: dict[str, list[dict[str, Any]]],
    expected_namespace: str,
    image_names: set[str],
) -> None:
    """Validate Deployment image and Kube-OVN annotation contracts.

    Args:
        by_kind: Manifest documents grouped by kind.
        expected_namespace: Namespace expected from the example compiler.
        image_names: Logical image names loaded from images.yaml.
    """
    for deployment in by_kind.get("Deployment", []):
        metadata = deployment.get("metadata") or {}
        name = str(metadata.get("name") or "")
        if metadata.get("namespace") != expected_namespace:
            fail(f"Deployment {name} must be in namespace {expected_namespace}")
        containers = (
            ((deployment.get("spec") or {}).get("template") or {})
            .get("spec", {})
            .get("containers", [])
        )
        if len(containers) != 1:
            fail(f"Deployment {name} expected one main container, got {len(containers)}")
        image = str(containers[0].get("image") or "")
        if image not in image_names:
            fail(f"Deployment {name} image {image} missing from images.yaml")
        annotations = podTemplateAnnotations(deployment)
        raw_networks = annotations.get("k8s.v1.cni.cncf.io/networks")
        if not isinstance(raw_networks, str):
            fail(f"Deployment {name} lacks Multus network annotation")
        try:
            networks = json.loads(raw_networks)
        except json.JSONDecodeError as exc:
            fail(f"Deployment {name} network annotation is not JSON: {exc}")
        if not isinstance(networks, list) or not networks:
            fail(f"Deployment {name} network annotation must be a non-empty list")
        for network in networks:
            if not isinstance(network, dict):
                fail(f"Deployment {name} contains non-mapping network selection")
            if "ips" in network:
                fail(f"Deployment {name} still contains macvlan-style ips field")
            nad_name = str(network.get("name") or "")
            nad_namespace = str(network.get("namespace") or expected_namespace)
            key = f"{nad_name}.{nad_namespace}.ovn.kubernetes.io/ip_address"
            if key not in annotations:
                fail(f"Deployment {name} lacks Kube-OVN IP annotation {key}")


def validateImages(images: list[dict[str, str]], output_dir: Path, image_registry_prefix: str) -> set[str]:
    """Validate image entries and Docker build contexts.

    Args:
        images: Parsed images.yaml entries.
        output_dir: Compiler output directory.
        image_registry_prefix: Expected logical image prefix.
    """
    image_names: set[str] = set()
    logical_prefix = image_registry_prefix.rstrip("/") + "/"
    for item in images:
        image = item["name"].strip()
        context = item["context"].strip()
        if not image.startswith(logical_prefix):
            fail(f"image {image} must start with {logical_prefix}")
        if image in image_names:
            fail(f"duplicate image entry {image}")
        image_names.add(image)
        context_path = Path(context)
        if context_path.is_absolute():
            fail(f"image {image} context must be relative, got {context}")
        resolved_context = (output_dir / context_path).resolve()
        try:
            resolved_context.relative_to(output_dir.resolve())
        except ValueError:
            fail(f"image {image} context escapes output directory: {context}")
        if not (resolved_context / "Dockerfile").is_file():
            fail(f"image {image} context lacks Dockerfile: {context}")
    return image_names


def validateNoHostLocalText(output_dir: Path) -> None:
    """Reject host-local absolute paths in generated text artifacts.

    Args:
        output_dir: Compiler output directory.
    """
    for path in output_dir.rglob("*"):
        if not path.is_file() or path.suffix == ".tar":
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for token in FORBIDDEN_TEXT:
            if token in text:
                fail(f"{path.relative_to(output_dir)} contains host-local path {token}")


def main() -> int:
    """Run native K8s compile-output validation."""
    args = parseArgs()
    output_dir = args.output_dir.expanduser().resolve()
    manifest_path = output_dir / MANIFEST_NAME
    images_path = output_dir / IMAGES_NAME
    legacy_manifest_path = output_dir / LEGACY_MANIFEST_NAME

    if not manifest_path.is_file():
        fail(f"missing {MANIFEST_NAME}")
    if not images_path.is_file():
        fail(f"missing {IMAGES_NAME}")
    if legacy_manifest_path.exists():
        fail(f"{LEGACY_MANIFEST_NAME} should not be generated for Kube-OVN output")

    docs = loadYamlDocuments(manifest_path)
    images = loadImages(images_path)
    by_kind = indexKinds(docs)
    image_names = validateImages(images, output_dir, args.image_registry_prefix)

    validateRequiredKinds(by_kind)
    validateNamespace(by_kind, args.expected_namespace)
    validateVpcAndSubnets(by_kind)
    validateNetworkAttachments(by_kind)
    validateDeployments(by_kind, args.expected_namespace, image_names)
    validateNoHostLocalText(output_dir)

    print(
        "Validated native K8s output: "
        f"{len(docs)} manifest documents, {len(images)} image contexts."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
