#!/usr/bin/env python3
# encoding: utf-8

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any, Dict, List


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from seedemu.compiler import Docker, Platform
from seedemu.core import Emulator
from seedemu.layers import Base, Ebgp, Ibgp, Ospf, PeerRelationship, Routing
from seedemu.utilities import Makers, AutonomousSystemLocationGenerator, AutonomousSystemTopologyGenerator


DEFAULT_IXES = [100, 101, 102]
DEFAULT_STUB_ASNS = [150, 151, 152]

# These locations are only anchors for visualization and metadata. They do not
# affect the physical links or routing configuration generated by SEED.
DEFAULT_ROUTER_LOCATIONS = {
    "r0": {"lat": 40.7128, "lon": -74.0060, "label": "New York"},
    "r1": {"lat": 41.8781, "lon": -87.6298, "label": "Chicago"},
    "r2": {"lat": 34.0522, "lon": -118.2437, "label": "Los Angeles"},
}


def parse_graph_param(value: str) -> tuple[str, Any]:
    """Parse --graph-param KEY=VALUE and preserve basic numeric/bool types."""
    if "=" not in value:
        raise argparse.ArgumentTypeError("graph parameters must use KEY=VALUE")

    key, raw_value = value.split("=", 1)
    key = key.strip()
    raw_value = raw_value.strip()
    if not key:
        raise argparse.ArgumentTypeError("graph parameter key cannot be empty")

    if raw_value.lower() in {"true", "false"}:
        return key, raw_value.lower() == "true"

    try:
        return key, int(raw_value)
    except ValueError:
        pass

    try:
        return key, float(raw_value)
    except ValueError:
        return key, raw_value


def parse_csv_ints(value: str) -> List[int]:
    items = [item.strip() for item in value.split(",") if item.strip()]
    if not items:
        raise argparse.ArgumentTypeError("value must contain at least one integer")
    return [int(item) for item in items]


def parse_router_location(value: str):
    """Parse --router-location ROUTER=LAT,LON into the location format used below."""
    if "=" not in value:
        raise argparse.ArgumentTypeError("router locations must use ROUTER=LAT,LON")

    router, raw_location = value.split("=", 1)
    router = router.strip()
    coordinates = [item.strip() for item in raw_location.split(",") if item.strip()]
    if not router or len(coordinates) != 2:
        raise argparse.ArgumentTypeError("router locations must use ROUTER=LAT,LON")

    try:
        return router, {"lat": float(coordinates[0]), "lon": float(coordinates[1])}
    except ValueError as exc:
        raise argparse.ArgumentTypeError("router location coordinates must be numbers") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a transit AS with a generated internal topology.")
    parser.add_argument("legacy_platform", nargs="?", choices=["amd", "arm"])
    parser.add_argument("--platform", choices=["amd", "arm"])
    parser.add_argument("--output", default=str(SCRIPT_DIR / "output"))
    parser.add_argument("--dumpfile")
    parser.add_argument("--override", dest="override", action="store_true", default=True)
    parser.add_argument("--no-override", dest="override", action="store_false")
    parser.add_argument("--skip-render", dest="render", action="store_false", default=True)

    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--asn", type=int, default=2)
    parser.add_argument("--ixes", type=parse_csv_ints, default=DEFAULT_IXES)
    parser.add_argument("--stub-asns", type=parse_csv_ints, default=DEFAULT_STUB_ASNS)
    parser.add_argument("--ebgp-routers", type=int)
    parser.add_argument("--hosts-per-stub", type=int, default=1)
    parser.add_argument("--internal-routers", type=int, default=4)
    parser.add_argument("--graph-model", default="small_world")
    parser.add_argument("--graph-param", action="append", type=parse_graph_param, default=[])
    parser.add_argument(
        "--ebgp-attach-policy",
        choices=["spread", "round_robin", "random", "degree"],
        default="spread",
    )
    parser.add_argument(
        "--internal-routing",
        choices=["full-mesh", "rr", "route-reflector"],
        default="full-mesh",
        help="iBGP design inside the generated AS.",
    )
    parser.add_argument(
        "--route-reflector",
        help="Router name to use as the route reflector in rr mode. Defaults to a high-degree internal router.",
    )
    parser.add_argument(
        "--router-location",
        action="append",
        type=parse_router_location,
        default=[],
        metavar="ROUTER=LAT,LON",
        help="Known router location used to anchor generated positions. Can be repeated.",
    )
    parser.add_argument(
        "--no-locations",
        dest="locations",
        action="store_false",
        default=True,
        help="Do not generate router location artifacts.",
    )

    args = parser.parse_args()

    # Keep compatibility with older examples that accepted the platform as the
    # first positional argument, while allowing the newer --platform option.
    args.platform = args.platform or args.legacy_platform or "amd"

    # Convert repeated parser options into dictionaries that are easier to pass
    # into the topology and location generators.
    args.graph_params = dict(args.graph_param)
    args.router_locations = dict(args.router_location)

    # A15 maps each generated eBGP router to one IX, so when the user does not
    # provide --ebgp-routers, the IX count defines the eBGP-router count.
    args.ebgp_routers = args.ebgp_routers or len(args.ixes)
    if args.internal_routing == "route-reflector":
        args.internal_routing = "rr"
    if len(args.ixes) != len(args.stub_asns):
        parser.error("--ixes and --stub-asns must contain the same number of entries")
    if args.ebgp_routers != len(args.ixes):
        parser.error("this example maps one eBGP router to one IX, so --ebgp-routers must match --ixes")
    return args


def resolve_platform(name: str) -> Platform:
    return Platform.AMD64 if name == "amd" else Platform.ARM64


def build_emulator(args: argparse.Namespace):
    emu = Emulator()
    base = Base()
    ebgp = Ebgp()

    # IXes are created first because the generated border routers and stub ASes
    # join these peering LANs later.
    for ix in args.ixes:
        base.createInternetExchange(ix)

    # Generate the abstract AS topology first. This object knows routers, links,
    # and eBGP-to-internal attachments, but it is still independent from SEED's
    # Base layer until apply_topology() below.
    topology = AutonomousSystemTopologyGenerator(
        ebgp_router_count=args.ebgp_routers,
        internal_router_count=args.internal_routers,
        graph_model=args.graph_model,
        graph_params=args.graph_params,
        ebgp_attach_policy=args.ebgp_attach_policy,
        seed=args.seed,
        ebgp_router_prefix="r",
    ).generate()

    # Materialize the generated topology into the SEED Base layer. After this
    # step, routers and networks exist in the emulator.
    transit_as = apply_topology(base, topology, args.asn, args.ixes)

    # Configure the iBGP control plane independently from the physical topology.
    # Full mesh needs no extra metadata; route-reflector mode marks one router
    # as the reflector and puts all AS routers into the same BGP cluster.
    internal_routing = configure_internal_routing(
        transit_as,
        topology,
        mode=args.internal_routing,
        route_reflector=args.route_reflector,
    )

    # Locations are generated after the topology is known. They are then written
    # both to topology artifacts and to Docker Compose labels via setLabel().
    locations = generate_locations(topology, args)
    if locations is not None:
        apply_location_metadata(transit_as, locations)

    # Stub ASes are created after the transit AS. Each stub joins the matching IX
    # and peers privately with the generated transit AS.
    for stub_asn, ix in zip(args.stub_asns, args.ixes):
        Makers.makeStubAsWithHosts(emu, base, stub_asn, ix, args.hosts_per_stub)
        ebgp.addPrivatePeering(ix, args.asn, stub_asn, PeerRelationship.Provider)

    emu.addLayer(base)
    emu.addLayer(Routing())
    emu.addLayer(ebgp)
    emu.addLayer(Ibgp())
    emu.addLayer(Ospf())
    return emu, topology, internal_routing, locations


def apply_topology(base: Base, topology, asn: int, ixes: List[int]):
    transit_as = base.createAutonomousSystem(asn)

    # Create every router before joining networks, so link creation can refer to
    # both endpoints regardless of edge ordering in the generated graph.
    routers = {name: transit_as.createRouter(name) for name in topology.routers()}

    # The topology generator only says which routers are eBGP routers. This
    # example decides how to map those routers onto concrete IX numbers.
    for ebgp_router, ix in zip(topology.ebgp_routers(), ixes):
        routers[ebgp_router].joinNetwork("ix{}".format(ix))

    # Each graph edge becomes one point-to-point SEED network. The generator
    # provides compact network names that fit Linux's interface-name limit.
    for left, right, network in topology.link_networks():
        transit_as.createNetwork(network)
        routers[left].joinNetwork(network)
        routers[right].joinNetwork(network)

    return transit_as


def configure_internal_routing(transit_as, topology, mode: str, route_reflector: str = None) -> Dict[str, Any]:
    mode = mode.lower()
    if mode == "full-mesh":
        # SEED's Ibgp layer creates a full mesh by default when no BGP clusters
        # are configured, so this mode only records metadata for artifacts.
        return {
            "mode": "full-mesh",
            "route_reflector": None,
            "description": "default SEED Ibgp() full mesh among AS routers",
        }

    if mode != "rr":
        raise ValueError("unsupported internal routing mode: {}".format(mode))

    # Use the provided router when the user wants a specific reflector; otherwise
    # choose a central internal router based on graph degree.
    rr_name = route_reflector or choose_route_reflector(topology)
    if rr_name not in set(topology.routers()):
        raise ValueError("unknown route reflector router: {}".format(rr_name))

    # All routers join one cluster. The selected router is marked as the route
    # reflector, and the rest become route-reflector clients.
    cluster_id = route_reflector_cluster_id(transit_as.getAsn())
    transit_as.createBgpCluster(cluster_id)
    for router_name in topology.routers():
        router = transit_as.getRouter(router_name).joinBgpCluster(cluster_id)
        if router_name == rr_name:
            router.makeRouteReflector()

    return {
        "mode": "rr",
        "route_reflector": rr_name,
        "cluster_id": cluster_id,
        "description": "one generated router is the route reflector; all other AS routers are clients",
    }


def choose_route_reflector(topology) -> str:
    # Prefer internal routers as RR candidates. The highest-degree router is a
    # reasonable default because it is central in the generated graph.
    graph = topology.graph()
    candidates = topology.internal_routers() or topology.routers()
    return sorted(candidates, key=lambda router: (-graph.degree(router), router))[0]


def route_reflector_cluster_id(asn: int) -> str:
    # BIRD expects a route-reflector cluster ID in IPv4-address form. Deriving it
    # from ASN keeps it deterministic and avoids another command-line option.
    return "10.{}.{}.1".format((int(asn) // 256) % 256, int(asn) % 256)


def generate_locations(topology, args: argparse.Namespace):
    if not args.locations:
        return None

    # Start with demonstration anchors, then let command-line anchors override
    # them. This keeps the default example useful while making experiments easy.
    fixed_locations = default_router_locations(topology)
    fixed_locations.update(args.router_locations)
    locations = AutonomousSystemLocationGenerator(
        fixed_locations=fixed_locations,
        seed=args.seed,
    ).generate(topology)

    # Preserve human-readable labels such as city names for fixed anchors. The
    # spring-layout generator only needs coordinates, but compose labels can use
    # this extra metadata.
    for router, fixed_location in fixed_locations.items():
        if isinstance(fixed_location, dict):
            label = fixed_location.get("label") or fixed_location.get("address")
            if label and router in locations:
                locations[router]["label"] = str(label)

    return locations


def default_router_locations(topology) -> Dict[str, Dict[str, Any]]:
    routers = set(topology.routers())
    return {
        router: location
        for router, location in DEFAULT_ROUTER_LOCATIONS.items()
        if router in routers
    }


def apply_location_metadata(transit_as, locations: Dict[str, Any]) -> None:
    # setGeo() keeps location metadata on the SEED node. setLabel() makes the
    # same metadata visible in docker-compose.yml for agents, tools, and tests.
    for router_name, location in locations.items():
        router = transit_as.getRouter(router_name)
        lat = float(location["lat"])
        lon = float(location["lon"])
        label = str(location.get("label", ""))

        router.setGeo(lat, lon, label)
        router.setLabel("geo.lat", "{:.6f}".format(lat))
        router.setLabel("geo.lon", "{:.6f}".format(lon))
        router.setLabel("geo.source", str(location.get("source", "generated")))
        if label:
            router.setLabel("geo.label", label)


def write_topology_artifacts(
    topology,
    output_dir: Path,
    internal_routing: Dict[str, Any],
    locations: Dict[str, Any] = None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    # topology.json is intended for tools and agents. It includes the generated
    # graph, routing mode, and optional location metadata in structured form.
    data = topology.to_dict()
    data["internal_routing"] = internal_routing
    if locations is not None:
        data["locations"] = locations
    with open(output_dir / "topology.json", "w", encoding="utf-8") as file:
        json.dump(data, file, indent=2, sort_keys=True)

    # topology.txt is a short human-readable summary for logs and quick checks.
    with open(output_dir / "topology.txt", "w", encoding="utf-8") as file:
        file.write(topology.summary())
        file.write("\n")
        file.write("internal routing: {}".format(internal_routing["mode"]))
        if internal_routing.get("route_reflector"):
            file.write(" via {} cluster {}".format(
                internal_routing["route_reflector"],
                internal_routing["cluster_id"],
            ))
        file.write("\n")
        if locations is not None:
            file.write("locations: {} routers\n".format(len(locations)))


def main() -> int:
    args = parse_args()
    emu, topology, internal_routing, locations = build_emulator(args)

    # A dumpfile is useful for debugging or composing emulators; it skips render
    # and Docker compilation by design.
    if args.dumpfile:
        emu.dump(args.dumpfile)
        return 0

    if args.render:
        emu.render()

    # Docker compilation happens last, after topology, routing metadata, and
    # location labels have all been attached to the emulator objects.
    output_dir = Path(args.output).resolve()
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    emu.compile(Docker(platform=resolve_platform(args.platform)), str(output_dir), override=args.override)
    write_topology_artifacts(topology, output_dir, internal_routing, locations)
    print(topology.summary())
    print("Internal routing mode: {}".format(internal_routing["mode"]))
    if internal_routing.get("route_reflector"):
        print("Route reflector: {} ({})".format(
            internal_routing["route_reflector"],
            internal_routing["cluster_id"],
        ))
    if locations is not None:
        print("Generated router locations for {} routers".format(len(locations)))
    print("Generated A15 Docker output in {}".format(output_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
