services:
  seedemu-ethexplorer-backend:
    build:
      context: beaconchain/backend
    image: handsonsecurity/seedemu-ethexplorer-backend:1.0
    container_name: seedemu_beaconchain_backend
    cap_add:
      - ALL
    pid: host
    privileged: true

  seedemu-ethexplorer-web:
    build:
      context: eth2-beaconchain-explorer/
    image: handsonsecurity/seedemu-ethexplorer-web:1.0
    container_name: seedemu_eth2_beaconchain_explorer
    cap_add:
      - ALL
    pid: host
    privileged: true
    ports:
      - 5000:5000

networks:
  beacon-network:
    driver: bridge