#!/usr/bin/env bash
# Validate that Kube-OVN non-primary CNI is ready for SeedEMU NADs.
#
# Args:
#   $1: Optional configK3s.yaml path. Defaults to ../configK3s.yaml.
#
# Inputs:
#   configK3s.yaml and the kubeconfig generated by buildK3sCluster.sh.
#
# Side effects:
#   None. This script only reads cluster state.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_PATH="${1:-${SETUP_DIR}/configK3s.yaml}"
HELPER="${SETUP_DIR}/manageK3sConfig.py"

if [ ! -s "${CONFIG_PATH}" ]; then
    echo "Missing config file: ${CONFIG_PATH}" >&2
    exit 1
fi

eval "$(python3 "${HELPER}" --config "${CONFIG_PATH}" shell-vars)"
eval "$(python3 "${HELPER}" --config "${CONFIG_PATH}" ovn-shell-vars)"

if [ "${fabricType}" != "ovn" ] && [ "${fabricType}" != "kube-ovn" ]; then
    echo "No Kube-OVN fabric configured; skipping OVN validation."
    exit 0
fi

if [ ! -s "${outputKubeconfig}" ]; then
    echo "Kubeconfig not found: ${outputKubeconfig}" >&2
    exit 1
fi

kubectl --kubeconfig "${outputKubeconfig}" -n "${ovnNamespace}" get pods -o wide
kubectl --kubeconfig "${outputKubeconfig}" wait --for=condition=Established crd/subnets.kubeovn.io --timeout=120s
kubectl --kubeconfig "${outputKubeconfig}" wait --for=condition=Established crd/vpcs.kubeovn.io --timeout=120s
kubectl --kubeconfig "${outputKubeconfig}" -n "${ovnNamespace}" rollout status deployment/kube-ovn-controller --timeout=300s
kubectl --kubeconfig "${outputKubeconfig}" -n "${ovnNamespace}" rollout status daemonset/kube-ovn-cni --timeout=300s
kubectl --kubeconfig "${outputKubeconfig}" -n "${ovnNamespace}" rollout status daemonset/ovs-ovn --timeout=300s
echo "Kube-OVN fabric validation passed."
